### ISSUE TITLE
<script> in views

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#13]
In your `User/index.html.erb`

It says it's a morris script - not sure what it's doing in raw format right there, but I'm guessing you're testing it or disabled it & forgot about it.

Comment me on what you want done with this thing?

These later should probably be moved to the /app/assets/javascript section ...
```

Searching for <script> in/app/views (Found 7 matches in 7 files)

/app/views/devise/registrations/new.html.erb:
	65: <script>

/app/views/devise/sessions/new.html.erb:
	49: <script>

/app/views/exercises/index.html.erb:
	62: <script>

/app/views/recipes/_disquis.html.erb:
	2: <script>

/app/views/users/index.html.erb:
	35: <script>

/app/views/users/show.html.erb:
	141: <script>

/app/views/workouts/_disquis.html.erb:
	2: <script>

Found 7 matches in 7 files
```

**Comment by jatwell93** [comment]
Not sure why i had that there :/ i've deleted it now.

**Comment by Mirv** [comment]
Sweet - just checking as I was vaguely trying to find why jquery executes twice :)
