### ISSUE TITLE
Title thing

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#17]
:Title thing

**Comment by jatwell93** [comment]
Thats sounds really cool! awesome idea.

**Comment by Mirv** [comment]
I was pondering this some & we could setup a helper to take in the `:title` that is provided & just insert that into the `<H?>` header tag automatically.  Since we already provide the title (I went and inserted it in most documents on your project `recipeVersion2` branch on either my git repo or yours), should be pretty straight forward.  The disadvantage is that the `:title` defaults to "A & K ..." which we can still test for to just say "everyone" or such...preference for either way?

Also second input from you on this issue - I need a list of names you want for each list or you to just go in and update with what you want in each section & I'll write the checks.  As some controllers, like `user` do more than just deal with users (which is fine for now, but we can move them later).
