### ISSUE TITLE
Unable to delete reviews 

### ISSUE THREAD

**Issue by jatwell93** [jatwell93/rubyproject#21]
Routing Error
No route matches [DELETE] "/recipes/1/review"

**Comment by Mirv** [comment]
I need the test suite working before we try trouble shooting - as with cascading changes - you often get regression errors & don't realize it unless you click every link every time you make a change.

**Comment by jatwell93** [comment]
thought this would also be fixed by the ujs being added back in but still an issue

**Comment by Mirv** [comment]
If the redirect after is giving the error & fixed, lets go ahead and close these.
