### ISSUE TITLE
A question before I go further

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#22]
Is this repo up to date with all of your changes from other machine to avoid conflicts or us both fixing the same issue?  

Is the c9 the only development env you have?  You're not programming locally on a computer somewhere?  I'll try to keep watch for pushes from other sources, but I forget sometimes.

@jatwell93

**Comment by Mirv** [comment]
@jatwell93

**Comment by jatwell93** [comment]
Hey @Mirv C9 is the only development environment i use. The repo is all update now just merged your branch then

**Comment by Mirv** [comment]
I'm going to keep doing pull requests on it then...starting with getting the test suite situated again.  I looked everywhere on that & couldn't find the code calling comments very easily so had to brute force it with find & comment out everything :(
