### ISSUE TITLE
Unable to delete recipes or workouts

### ISSUE THREAD

**Issue by jatwell93** [jatwell93/rubyproject#25]
everything appears to work, however the recipe or workout is not actually deleted. Have checked the code in the views and seems to be right, now will move on to the controllers

**Comment by Mirv** [comment]
Good call -  when I see stuff isn't deleting in nested forms (accepts_for), I go right to check strong_params & models

**Comment by jatwell93** [comment]
made a slight change to the controller which i thought would fix it however hasnt seemed to. will check the models and strong params now

**Comment by Mirv** [comment]
If you link to the commit in here by just typing the number or doing a copy paste - then I can see what you're talking about :)

**Comment by Mirv** [comment]
Random thought ... 

Do you use <% debug @<whateverControllerVariable> %>?  I'm guessing that the object isn't being set & thus the `.delete` doesn't exists (that's what many .nil or .null object errors are)

**Comment by jatwell93** [comment]
no i've never used that i'll have to do some googling on how that works. I'm guessing it'll show you what object is being generated?

**Comment by Mirv** [comment]
Ok, so when I look at this - the deletion works - but after deleting it looks like you are routing them back to the ID # you just deleted.  That's my quick glance right now.

**Comment by jatwell93** [comment]
yeh i just fixed that so it routes back to the previous page. another error gone!

**Comment by Mirv** [comment]
w00t!
