### ISSUE TITLE
Relationship:  Recipe to Ingredients

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#29]
Ok, so in testing, there's no easy way to validate ingredients in a recipe (I agree it makes sense to do so)...but it cued me in on another codesmell ...

You have a single recipe being the so owner of an ingredient ... can't a pie have an apple & an apple still be part of apple cobbler?

We should probably have a has_many through relationship for them.

**Comment by jatwell93** [comment]
definitely agree, i'll have to do some reading on has_many through relationships, it's not something i've used. 

the whole ingredients part has sort of fallen apart due to that issue

**Comment by Mirv** [comment]
The falling apart is painful!

The has_many: :through is pretty straight forward once you get the idea in the head.  It's basically chaining to associations together.
```
snack.rb
  
  has_many: cheetos
  has_many: bags, through: :cheetos
```

In this way, the snack model can get as many cheetos as it wants via the bags association (relationship).

When we call it - it's just 
```
@snack = Bags.all
@snack  # returns a collection list (activerecord obj) of all entries on bag
@first_snack = @snack.cheetos.first  # returns single entry from table
@id = @first_snack.id
@name = @first_snack.name
```

Technically `SOLID` principles say we shouldn't, but you totally could keep chaining for one liners (though there's often better ways).

```
@name = @snacks.first.id  # totally a thing, though rails conventions say send the whole obj, as often programs change
```

**Comment by Mirv** [comment]
This one is a bit older but solid into to the idea - https://www.sitepoint.com/complex-rails-forms-with-nested-attributes/

**Comment by Mirv** [comment]
BTW:  You already have a has_many through relationship ... it's in recipe controller ...

```
    has_many    :recipe_preptimes
    has_many    :preptimes, through: :recipe_preptimes
```

**Comment by jatwell93** [comment]
Oh ok i have read a bit about them before actually, i'll do some brushing up on it today especially around implementation. 

ah yes i had a feeling they might be in there, it was one of the first parts of the tutorial i was following so i don't really remember too much about it.
