### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#45]
I made a project called tracking - it's on the  same row as the "Issues" button.

I made a wiki page for use too ... https://github.com/jatwell93/rubyproject/wiki/Project-conventions

**Comment by jatwell93** [comment]
Thats awesome! Makes me feel like we're really making some headway

**Comment by Mirv** [comment]
It gets impossible to track without this stuff - any day you get really down - just go through the closed items and make cards for one or two of them - then put them in the completed section :)
